---
title: "Loan Default"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
data <- read.csv("C://Users/PC2//Downloads//wdbc.data",header = F,col.names = c("ID","Diagnosis","Radius Mean", "Texture Mean", "Perimeter Mean", "Area Mean", "Smoothness Mean",  "Compactness Mean", "Concavity Mean","Concave points Mean", "Symmetry Mean","FractalDimension Mean","Radius SE", "Texture SE", "Perimeter SE", "Area SE", "Smoothness SE",  "Compactness SE", "Concavity SE","Concave Points SE", "Symmetry SE","FractalDimension SE","Radius W", "Texture W", "Perimeter W", "Area W", "Smoothness W",  "Compactness W", "Concavity W","Concave Points W", "Symmetry W","FractalDimension W") )

data <- data[sample(nrow(data)),]

```

```{r}
#Factors
data$Diagnosis <- factor(data$Diagnosis, labels = c("Benign", "Malignant"))

#Normalization
normalize <-function(x){
  return((x - min(x))/(max(x) - min(x)))
}

data_nor <- as.data.frame(lapply(data[3:32], normalize))

#applying k means

train <- data_nor[1:469,]
test  <- data_nor[470:nrow(data_nor),]
labels_train <- data$Diagnosis[1:469]
labels_test <- data$Diagnosis[470:nrow(data_nor)]

install.packages("class")
library("class")
prediction <- knn(train = train, test = test ,labels_train, k = round(sqrt(nrow(train)),digits = 0))
CrossTable(x = labels_test, y = prediction, prop.chisq = F)
```

```{r}
#Alternate Method

#USing  Z Score Normalization - Possibly good if malignant tumours give large values 
data_z <- as.data.frame(scale(data[3:32]))
train <- data_z[1:469,]
test  <- data_z[470:nrow(data_nor),]
labels_train <- data$Diagnosis[1:469]
labels_test <- data$Diagnosis[470:nrow(data_nor)]
prediction <- knn(train = train, test = test ,labels_train, k = round(sqrt(nrow(train)),digits = 0))
CrossTable(x = labels_test, y = prediction, prop.chisq = F)
#Peforms slightly better than previous normalization

#Using different values for k

for(i in 1:25)
{
  prediction <- knn(train = train, test = test ,labels_train, k = i)
  ctable <- CrossTable(x = labels_test, y = prediction, prop.chisq = F)
  print(ctable$t[2])
}
```


